# Generated by Django 4.1 on 2023-09-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driverwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverid', models.CharField(max_length=2080)),
                ('corporatename', models.CharField(max_length=2080)),
                ('location', models.CharField(max_length=2080)),
                ('gatepassno', models.CharField(max_length=2080)),
                ('date', models.CharField(max_length=2080)),
                ('id_no', models.CharField(max_length=2080)),
                ('name', models.CharField(max_length=2080)),
                ('pickupplace', models.CharField(max_length=2080)),
                ('dropplace', models.CharField(max_length=2080)),
                ('vehicleno', models.CharField(max_length=2080)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('imgbb_url', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='driverid',
        ),
    ]
