# Generated by Django 4.2.4 on 2023-10-27 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_driverwork_trip1_driverwork_trip2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverwork',
            name='id_no',
        ),
    ]
