# Generated by Django 4.1 on 2023-10-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverwork',
            name='trip1',
        ),
        migrations.RemoveField(
            model_name='driverwork',
            name='trip2',
        ),
    ]
